In [ ]:
# Fill binary values with 0 and 1 insteas of categories

In [1]:
import pandas as pd

In [2]:
cleaned_data = pd.read_csv("../data/clean_icfes_data_cesar.csv")
df = cleaned_data.copy()
df

,periodo,estu_tipodocumento,estu_consecutivo,cole_area_ubicacion,cole_bilingue,cole_calendario,cole_caracter,cole_cod_dane_establecimiento,cole_cod_dane_sede,cole_cod_depto_ubicacion,...,fami_tienecomputador,fami_tieneinternet,fami_tienelavadora,desemp_ingles,punt_ingles,punt_matematicas,punt_sociales_ciudadanas,punt_c_naturales,punt_lectura_critica,punt_global
0,20224,TI,SB11202240346555,URBANO,NaN,A,TÉCNICO/ACADÉMICO,120228000642,120228000642,20,...,No,No,Si,A-,39.0,39.0,42.0,37.0,56.0,216.0
1,20224,TI,SB11202240587156,URBANO,N,A,ACADÉMICO,120001006768,120001006768,20,...,No,Si,Si,A-,42.0,49.0,48.0,45.0,47.0,234.0
2,20224,TI,SB11202240047096,URBANO,NaN,A,ACADÉMICO,220060000069,220060000069,20,...,Si,NaN,Si,A1,50.0,50.0,52.0,41.0,55.0,248.0
3,20224,CC,SB11202240362450,URBANO,N,A,TÉCNICO/ACADÉMICO,120383000004,120383000004,20,...,No,NaN,Si,A1,50.0,50.0,42.0,47.0,45.0,232.0
4,20224,TI,SB11202240373694,RURAL,N,A,ACADÉMICO,220001067435,220001067435,20,...,No,Si,Si,A1,55.0,65.0,56.0,67.0,54.0,300.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77570,20162,TI,SB11201620486055,URBANO,N,A,ACADÉMICO,120001000921,120001000921,20,...,No,No,No,B1,71.0,74.0,61.0,70.0,58.0,331.0
77571,20162,TI,SB11201620525906,URBANO,N,A,TÉCNICO/ACADÉMICO,120400000111,120400000111,20,...,No,No,Si,A2,63.0,55.0,54.0,54.0,53.0,273.0
77572,20142,TI,SB11201420185350,RURAL,N,A,ACADÉMICO,220013000395,220013000395,20,...,Si,No,No,A-,41.0,52.0,41.0,42.0,43.0,221.0
77573,20142,TI,SB11201420586016,URBANO,N,A,TÉCNICO,120001068194,120001068194,20,...,No,No,Si,A-,41.0,38.0,40.0,37.0,41.0,196.0
77574,20194,TI,SB11201940513265,URBANO,N,A,TÉCNICO/ACADÉMICO,120045000210,120045000210,20,...,Si,Si,Si,A-,38.0,39.0,31.0,35.0,33.0,174.0

In [5]:
filtered_df = df[["periodo", "cole_area_ubicacion", "cole_bilingue", "cole_calendario", 
                  "cole_caracter", "cole_cod_dane_establecimiento", "cole_cod_dane_sede", # TODO: see if we remove cod Dane establecimiento and sede, because they are not useful for the model, but we can use them for EDA
                  "cole_cod_mcpio_ubicacion", "cole_jornada", "cole_naturaleza", # cole_genero removed because all are MIXTO
                  "estu_cod_reside_depto", "estu_cod_reside_mcpio", "estu_estadoinvestigacion", 
                  "estu_fechanacimiento", "estu_genero", "estu_nacionalidad", # TODO: Ver si dejamos nacionalidad, pues hay poquitos 
                  "fami_cuartoshogar", "fami_educacionmadre", "fami_educacionpadre", 
                  "fami_estratovivienda", "fami_personashogar", "fami_tieneautomovil", 
                  "fami_tienecomputador", "fami_tieneinternet", "fami_tienelavadora", 
                  "desemp_ingles", "punt_ingles", "punt_matematicas", 
                  "punt_sociales_ciudadanas", "punt_c_naturales", "punt_lectura_critica", 
                  "punt_global"
                  ]]
filtered_df

,periodo,cole_area_ubicacion,cole_bilingue,cole_calendario,cole_caracter,cole_cod_dane_establecimiento,cole_cod_dane_sede,cole_cod_mcpio_ubicacion,cole_jornada,cole_naturaleza,...,fami_tienecomputador,fami_tieneinternet,fami_tienelavadora,desemp_ingles,punt_ingles,punt_matematicas,punt_sociales_ciudadanas,punt_c_naturales,punt_lectura_critica,punt_global
0,20224,URBANO,NaN,A,TÉCNICO/ACADÉMICO,120228000642,120228000642,20228,MAÑANA,OFICIAL,...,No,No,Si,A-,39.0,39.0,42.0,37.0,56.0,216.0
1,20224,URBANO,N,A,ACADÉMICO,120001006768,120001006768,20001,MAÑANA,OFICIAL,...,No,Si,Si,A-,42.0,49.0,48.0,45.0,47.0,234.0
2,20224,URBANO,NaN,A,ACADÉMICO,220060000069,220060000069,20060,MAÑANA,OFICIAL,...,Si,NaN,Si,A1,50.0,50.0,52.0,41.0,55.0,248.0
3,20224,URBANO,N,A,TÉCNICO/ACADÉMICO,120383000004,120383000004,20383,MAÑANA,OFICIAL,...,No,NaN,Si,A1,50.0,50.0,42.0,47.0,45.0,232.0
4,20224,RURAL,N,A,ACADÉMICO,220001067435,220001067435,20001,UNICA,OFICIAL,...,No,Si,Si,A1,55.0,65.0,56.0,67.0,54.0,300.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77570,20162,URBANO,N,A,ACADÉMICO,120001000921,120001000921,20001,TARDE,OFICIAL,...,No,No,No,B1,71.0,74.0,61.0,70.0,58.0,331.0
77571,20162,URBANO,N,A,TÉCNICO/ACADÉMICO,120400000111,120400000111,20400,TARDE,OFICIAL,...,No,No,Si,A2,63.0,55.0,54.0,54.0,53.0,273.0
77572,20142,RURAL,N,A,ACADÉMICO,220013000395,220013000395,20013,MAÑANA,OFICIAL,...,Si,No,No,A-,41.0,52.0,41.0,42.0,43.0,221.0
77573,20142,URBANO,N,A,TÉCNICO,120001068194,120001068194,20001,MAÑANA,OFICIAL,...,No,No,Si,A-,41.0,38.0,40.0,37.0,41.0,196.0
77574,20194,URBANO,N,A,TÉCNICO/ACADÉMICO,120045000210,120045000210,20045,MAÑANA,OFICIAL,...,Si,Si,Si,A-,38.0,39.0,31.0,35.0,33.0,174.0

In [6]:
# Set column types to clean nulls

filtered_df["estu_fechanacimiento"] = pd.to_datetime(
    filtered_df["estu_fechanacimiento"],
    errors="coerce",
    dayfirst=True
)

# Set column types to clean nulls
filtered_df = filtered_df.astype({
    "periodo": "category",

    "cole_area_ubicacion": "category", # boolean in the future
    "cole_bilingue": "category", # boolean in the future
    "cole_calendario": "category", # boolean in the future
    "cole_caracter": "category",

    "cole_cod_dane_establecimiento": "string",
    "cole_cod_dane_sede": "string",
    "cole_cod_mcpio_ubicacion": "string",

    "cole_jornada": "category",
    "cole_naturaleza": "category", # boolean in the future

    "estu_cod_reside_depto": "string", # keep only 20
    "estu_cod_reside_mcpio": "string",

    "estu_estadoinvestigacion": "category", # keep only PUBLICAR

    # estu_fechanacimiento handled above with pd.to_datetime(errors="coerce")

    "estu_genero": "category", # boolean in the future
    "estu_nacionalidad": "category",

    "fami_cuartoshogar": "string", # clean and send to category later

    "fami_educacionmadre": "category", # TODO: see if we can scale this variable since it has order
    "fami_educacionpadre": "category", # TODO: see if we can scale this variable since it has order
    "fami_estratovivienda": "category", # TODO: see if we can scale this variable since it has order

    "fami_personashogar": "category", # clean and send to category/int later

    "fami_tieneautomovil": "category", # boolean in the future
    "fami_tienecomputador": "category", # boolean in the future
    "fami_tieneinternet": "category", # boolean in the future
    "fami_tienelavadora": "category", # boolean in the future

    "desemp_ingles": "category", # TODO: see if we can scale this variable since it has order

    # Nullable integers
    "punt_ingles": "Int64",
    "punt_matematicas": "Int64",
    "punt_sociales_ciudadanas": "Int64",
    "punt_c_naturales": "Int64",
    "punt_lectura_critica": "Int64",
    "punt_global": "Int64"
})
filtered_df

,periodo,cole_area_ubicacion,cole_bilingue,cole_calendario,cole_caracter,cole_cod_dane_establecimiento,cole_cod_dane_sede,cole_cod_mcpio_ubicacion,cole_jornada,cole_naturaleza,...,fami_tienecomputador,fami_tieneinternet,fami_tienelavadora,desemp_ingles,punt_ingles,punt_matematicas,punt_sociales_ciudadanas,punt_c_naturales,punt_lectura_critica,punt_global
0,20224,URBANO,NaN,A,TÉCNICO/ACADÉMICO,120228000642,120228000642,20228,MAÑANA,OFICIAL,...,No,No,Si,A-,39,39,42,37,56,216
1,20224,URBANO,N,A,ACADÉMICO,120001006768,120001006768,20001,MAÑANA,OFICIAL,...,No,Si,Si,A-,42,49,48,45,47,234
2,20224,URBANO,NaN,A,ACADÉMICO,220060000069,220060000069,20060,MAÑANA,OFICIAL,...,Si,NaN,Si,A1,50,50,52,41,55,248
3,20224,URBANO,N,A,TÉCNICO/ACADÉMICO,120383000004,120383000004,20383,MAÑANA,OFICIAL,...,No,NaN,Si,A1,50,50,42,47,45,232
4,20224,RURAL,N,A,ACADÉMICO,220001067435,220001067435,20001,UNICA,OFICIAL,...,No,Si,Si,A1,55,65,56,67,54,300
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77570,20162,URBANO,N,A,ACADÉMICO,120001000921,120001000921,20001,TARDE,OFICIAL,...,No,No,No,B1,71,74,61,70,58,331
77571,20162,URBANO,N,A,TÉCNICO/ACADÉMICO,120400000111,120400000111,20400,TARDE,OFICIAL,...,No,No,Si,A2,63,55,54,54,53,273
77572,20142,RURAL,N,A,ACADÉMICO,220013000395,220013000395,20013,MAÑANA,OFICIAL,...,Si,No,No,A-,41,52,41,42,43,221
77573,20142,URBANO,N,A,TÉCNICO,120001068194,120001068194,20001,MAÑANA,OFICIAL,...,No,No,Si,A-,41,38,40,37,41,196
77574,20194,URBANO,N,A,TÉCNICO/ACADÉMICO,120045000210,120045000210,20045,MAÑANA,OFICIAL,...,Si,Si,Si,A-,38,39,31,35,33,174

In [8]:
# Clean all rows with any null values already present in the data
filtered_df = filtered_df.dropna(axis=0, how="any").reset_index(drop=True)
filtered_df

,periodo,cole_area_ubicacion,cole_bilingue,cole_calendario,cole_caracter,cole_cod_dane_establecimiento,cole_cod_dane_sede,cole_cod_mcpio_ubicacion,cole_jornada,cole_naturaleza,...,fami_tienecomputador,fami_tieneinternet,fami_tienelavadora,desemp_ingles,punt_ingles,punt_matematicas,punt_sociales_ciudadanas,punt_c_naturales,punt_lectura_critica,punt_global
0,20224,URBANO,N,A,ACADÉMICO,120001006768,120001006768,20001,MAÑANA,OFICIAL,...,No,Si,Si,A-,42,49,48,45,47,234
1,20224,RURAL,N,A,ACADÉMICO,220001067435,220001067435,20001,UNICA,OFICIAL,...,No,Si,Si,A1,55,65,56,67,54,300
2,20224,RURAL,N,A,TÉCNICO/ACADÉMICO,220175017801,220175017801,20175,UNICA,OFICIAL,...,No,No,No,A-,44,44,45,34,48,214
3,20224,URBANO,N,A,TÉCNICO,120001001201,120001001201,20001,TARDE,OFICIAL,...,Si,Si,Si,A-,41,40,36,42,50,210
4,20224,URBANO,N,A,TÉCNICO/ACADÉMICO,120295000061,120295000061,20295,UNICA,OFICIAL,...,No,No,Si,A-,31,40,30,33,44,182
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63316,20162,URBANO,N,A,ACADÉMICO,120001000921,120001000921,20001,TARDE,OFICIAL,...,No,No,No,B1,71,74,61,70,58,331
63317,20162,URBANO,N,A,TÉCNICO/ACADÉMICO,120400000111,120400000111,20400,TARDE,OFICIAL,...,No,No,Si,A2,63,55,54,54,53,273
63318,20142,RURAL,N,A,ACADÉMICO,220013000395,220013000395,20013,MAÑANA,OFICIAL,...,Si,No,No,A-,41,52,41,42,43,221
63319,20142,URBANO,N,A,TÉCNICO,120001068194,120001068194,20001,MAÑANA,OFICIAL,...,No,No,Si,A-,41,38,40,37,41,196
63320,20194,URBANO,N,A,TÉCNICO/ACADÉMICO,120045000210,120045000210,20045,MAÑANA,OFICIAL,...,Si,Si,Si,A-,38,39,31,35,33,174

In [9]:
# export cleaned data to csv
filtered_df.to_csv("../data/filtered_icfes_data_cesar.csv", index=False)