In [85]:
import pandas as pd

pd.set_option("display.max_columns", None)

In [86]:
cleaned_data = pd.read_csv("../data/clean_icfes_data_cesar.csv")
df = cleaned_data.copy()
df

,periodo,estu_tipodocumento,estu_consecutivo,cole_area_ubicacion,cole_bilingue,cole_calendario,cole_caracter,cole_cod_dane_establecimiento,cole_cod_dane_sede,cole_cod_depto_ubicacion,cole_cod_mcpio_ubicacion,cole_codigo_icfes,cole_depto_ubicacion,cole_genero,cole_jornada,cole_mcpio_ubicacion,cole_naturaleza,cole_nombre_establecimiento,cole_nombre_sede,cole_sede_principal,estu_cod_depto_presentacion,estu_cod_mcpio_presentacion,estu_cod_reside_depto,estu_cod_reside_mcpio,estu_depto_presentacion,estu_depto_reside,estu_estadoinvestigacion,estu_estudiante,estu_fechanacimiento,estu_genero,estu_mcpio_presentacion,estu_mcpio_reside,estu_nacionalidad,estu_pais_reside,estu_privado_libertad,fami_cuartoshogar,fami_educacionmadre,fami_educacionpadre,fami_estratovivienda,fami_personashogar,fami_tieneautomovil,fami_tienecomputador,fami_tieneinternet,fami_tienelavadora,desemp_ingles,punt_ingles,punt_matematicas,punt_sociales_ciudadanas,punt_c_naturales,punt_lectura_critica,punt_global
0,20224,TI,SB11202240346555,URBANO,NaN,A,TÉCNICO/ACADÉMICO,120228000642,120228000642,20,20228,657767.0,CESAR,MIXTO,MAÑANA,CURUMANÍ,OFICIAL,INSTITUCION EDUCATIVA SAN ISIDRO,INSTITUCION EDUCATIVA SAN ISIDRO,S,20,20228,20.0,20228.0,CESAR,CESAR,PUBLICAR,ESTUDIANTE,29/01/2005,F,CURUMANÍ,CURUMANÍ,COLOMBIA,COLOMBIA,N,Cuatro,Secundaria (Bachillerato) completa,Secundaria (Bachillerato) completa,Estrato 2,3 a 4,No,No,No,Si,A-,39.0,39.0,42.0,37.0,56.0,216.0
1,20224,TI,SB11202240587156,URBANO,N,A,ACADÉMICO,120001006768,120001006768,20,20001,133041.0,CESAR,MIXTO,MAÑANA,VALLEDUPAR,OFICIAL,INSTITUCION EDUCATIVA BELLO HORIZONTE,BELLO HORIZONTE,S,20,20001,20.0,20001.0,CESAR,CESAR,PUBLICAR,ESTUDIANTE,07/09/2005,F,VALLEDUPAR,VALLEDUPAR,COLOMBIA,COLOMBIA,N,Dos,Primaria completa,Primaria incompleta,Estrato 4,3 a 4,Si,No,Si,Si,A-,42.0,49.0,48.0,45.0,47.0,234.0
2,20224,TI,SB11202240047096,URBANO,NaN,A,ACADÉMICO,220060000069,220060000069,20,20060,657494.0,CESAR,MIXTO,MAÑANA,BOSCONIA,OFICIAL,INSTITUCION EDUCATIVA SAN JUAN BOSCO,INSTITUCION EDUCATIVA SAN JUAN BOSCO,S,20,20060,20.0,20060.0,CESAR,CESAR,PUBLICAR,ESTUDIANTE,24/08/2004,F,BOSCONIA,BOSCONIA,COLOMBIA,COLOMBIA,N,Tres,NaN,NaN,NaN,7 a 8,No,Si,NaN,Si,A1,50.0,50.0,52.0,41.0,55.0,248.0
3,20224,CC,SB11202240362450,URBANO,N,A,TÉCNICO/ACADÉMICO,120383000004,120383000004,20,20383,131912.0,CESAR,MIXTO,MAÑANA,LA GLORIA,OFICIAL,INSTITUCION EDUCATIVA INTEGRADO,INSTITUCION EDUCATIVA INTEGRADO,S,20,20011,20.0,20383.0,CESAR,CESAR,PUBLICAR,ESTUDIANTE,14/09/2003,F,AGUACHICA,LA GLORIA,COLOMBIA,COLOMBIA,N,Uno,NaN,NaN,NaN,3 a 4,No,No,NaN,Si,A1,50.0,50.0,42.0,47.0,45.0,232.0
4,20224,TI,SB11202240373694,RURAL,N,A,ACADÉMICO,220001067435,220001067435,20,20001,719468.0,CESAR,MIXTO,UNICA,VALLEDUPAR,OFICIAL,INSTITUCION EDUCATIVA DE PATILLAL,IE PATILLAL,S,20,20001,20.0,20001.0,CESAR,CESAR,PUBLICAR,ESTUDIANTE,22/12/2006,M,VALLEDUPAR,VALLEDUPAR,COLOMBIA,COLOMBIA,N,Cuatro,Primaria completa,Secundaria (Bachillerato) incompleta,Estrato 1,3 a 4,Si,No,Si,Si,A1,55.0,65.0,56.0,67.0,54.0,300.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77570,20162,TI,SB11201620486055,URBANO,N,A,ACADÉMICO,120001000921,120001000921,20,20001,7633.0,CESAR,MIXTO,TARDE,VALLEDUPAR,OFICIAL,INSTITUCION EDUCATIVA PRUDENCIA DAZA,PRUDENCIA DAZA,S,20,20001,20.0,20001.0,CESAR,CESAR,PUBLICAR,ESTUDIANTE,12/05/2000,F,VALLEDUPAR,VALLEDUPAR,COLOMBIA,COLOMBIA,N,Dos,Primaria completa,Secundaria (Bachillerato) completa,Estrato 1,Cuatro,No,No,No,No,B1,71.0,74.0,61.0,70.0,58.0,331.0
77571,20162,TI,SB11201620525906,URBANO,N,A,TÉCNICO/ACADÉMICO,120400000111,120400000111,20,20400,99820.0,CESAR,MIXTO,TARDE,LA JAGUA DE IBIRICO,OFICIAL,INSTITUCION EDUCATIVA JOSE GUILLERMO CASTRO CA...,INST. EDU. JOSE GUILLERMO CASTRO CASTRO,S,20,20400,20.0,20400.0,CESAR,CESAR,PUBLICAR,ESTUDIANTE,17/03/1998,F,LA JAGUA DE IBIRICO,LA JAGUA DE IBIRICO,COLOMBIA,COLOMBIA,N,Uno,Secundaria (Bachillerato) incompleta,No sabe,Estrato 1,Dos,No,No,No,Si,A2,63.0,55.0,54.0,54.0,53.0,273.0
77572,20142,TI,SB11201420185350,RURAL,N,A,ACADÉMICO,220013000395,220013000395,20,20013,175554.0,CESAR,MIXTO,MAÑANA,AGUSTIN CODAZZI,OFICIAL,INSTITUCION EDUCATIVA SIMON BOLIVAR,I.E. SIMON BOLIVAR - SEDE PRINCIPAL,S,20,20013,20.0,20013.0,CESAR,CESAR,PUBLICAR,ESTUDIANTE,01/04/1996,M,AGUSTÍN CODAZZI,AGUSTÍN CODAZZI,COLOMBIA,COLOMBIA,N,Dos,Ninguno,Ninguno,Estrato 1,Siete,No,Si,No,No,A-,41.0,52.0,41.0,42.0,43.0,221.0
77573,20142,TI,SB11201420586016,URBANO,N,A,TÉCNICO,120001068194,120001068194,20,20001,96875.0,CESAR,MIXTO,MAÑANA,VALLEDUPAR,OFICIAL,INSTITUCION EDUCATIVA LA ESPERANZA,INST TEC LA ESPERANZA,S,20,20001,20.0,20001.0,CESAR,CESAR,PUBLICAR,ESTUDIANTE,15/09/1996,F,VALLEDUPAR,VALLEDUPAR,COLOMBIA,COLOMBIA,N,Dos,Ninguno,Ninguno,Estrato 1,Cuatro,No,No,No,Si,A-,41.0,38.0,40.0,37.0,41.0,196.0
77574,20194,TI,SB11201940513265,URBANO,N,A,TÉCNICO/ACADÉMICO,120045000210,120045000210,20,20045,36301.0,CESAR,MIXTO,MAÑANA,BECERRIL,OFICIAL,INSTITUCION EDUCATIVA ANGELA MARIA TORRES SUAREZ,I.E. ANGELA MARIA TORRES SUAREZ,S,20,20045,20.0,20045.0,CESAR,CESAR,PUBLICAR,ESTUDIANTE,20/08/2002,M,BECERRIL,BECERRIL,COLOMBIA,COLOMBIA,N,Tres,No sabe,Primaria incompleta,Estrato 3,1 a 2,Si,Si,Si,Si,A-,38.0,39.0,31.0,35.0,33.0,174.0

In [87]:
filtered_df = df[["periodo", "cole_area_ubicacion", "cole_bilingue", "cole_calendario", 
                  "cole_caracter", "cole_cod_dane_establecimiento", "cole_cod_dane_sede", # TODO: see if we remove cod Dane establecimiento and sede, because they are not useful for the model, but we can use them for EDA
                  "cole_cod_mcpio_ubicacion", "cole_jornada", "cole_naturaleza", # cole_genero removed because all are MIXTO
                  "estu_cod_reside_depto", "estu_cod_reside_mcpio", "estu_estadoinvestigacion", 
                  "estu_genero", "estu_nacionalidad", # TODO: Ver si dejamos nacionalidad, pues hay poquitos # Removed fecha nacimiento since many errors getting age
                  "fami_cuartoshogar", "fami_educacionmadre", "fami_educacionpadre", 
                  "fami_estratovivienda", "fami_personashogar", "fami_tieneautomovil", 
                  "fami_tienecomputador", "fami_tieneinternet", "fami_tienelavadora", 
                  "punt_ingles", "punt_matematicas", # Removed desemp_ingles since its linear with punt_ingles
                  "punt_sociales_ciudadanas", "punt_c_naturales", "punt_lectura_critica", 
                  "punt_global"
                  ]]
filtered_df

,periodo,cole_area_ubicacion,cole_bilingue,cole_calendario,cole_caracter,cole_cod_dane_establecimiento,cole_cod_dane_sede,cole_cod_mcpio_ubicacion,cole_jornada,cole_naturaleza,estu_cod_reside_depto,estu_cod_reside_mcpio,estu_estadoinvestigacion,estu_genero,estu_nacionalidad,fami_cuartoshogar,fami_educacionmadre,fami_educacionpadre,fami_estratovivienda,fami_personashogar,fami_tieneautomovil,fami_tienecomputador,fami_tieneinternet,fami_tienelavadora,punt_ingles,punt_matematicas,punt_sociales_ciudadanas,punt_c_naturales,punt_lectura_critica,punt_global
0,20224,URBANO,NaN,A,TÉCNICO/ACADÉMICO,120228000642,120228000642,20228,MAÑANA,OFICIAL,20.0,20228.0,PUBLICAR,F,COLOMBIA,Cuatro,Secundaria (Bachillerato) completa,Secundaria (Bachillerato) completa,Estrato 2,3 a 4,No,No,No,Si,39.0,39.0,42.0,37.0,56.0,216.0
1,20224,URBANO,N,A,ACADÉMICO,120001006768,120001006768,20001,MAÑANA,OFICIAL,20.0,20001.0,PUBLICAR,F,COLOMBIA,Dos,Primaria completa,Primaria incompleta,Estrato 4,3 a 4,Si,No,Si,Si,42.0,49.0,48.0,45.0,47.0,234.0
2,20224,URBANO,NaN,A,ACADÉMICO,220060000069,220060000069,20060,MAÑANA,OFICIAL,20.0,20060.0,PUBLICAR,F,COLOMBIA,Tres,NaN,NaN,NaN,7 a 8,No,Si,NaN,Si,50.0,50.0,52.0,41.0,55.0,248.0
3,20224,URBANO,N,A,TÉCNICO/ACADÉMICO,120383000004,120383000004,20383,MAÑANA,OFICIAL,20.0,20383.0,PUBLICAR,F,COLOMBIA,Uno,NaN,NaN,NaN,3 a 4,No,No,NaN,Si,50.0,50.0,42.0,47.0,45.0,232.0
4,20224,RURAL,N,A,ACADÉMICO,220001067435,220001067435,20001,UNICA,OFICIAL,20.0,20001.0,PUBLICAR,M,COLOMBIA,Cuatro,Primaria completa,Secundaria (Bachillerato) incompleta,Estrato 1,3 a 4,Si,No,Si,Si,55.0,65.0,56.0,67.0,54.0,300.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
77570,20162,URBANO,N,A,ACADÉMICO,120001000921,120001000921,20001,TARDE,OFICIAL,20.0,20001.0,PUBLICAR,F,COLOMBIA,Dos,Primaria completa,Secundaria (Bachillerato) completa,Estrato 1,Cuatro,No,No,No,No,71.0,74.0,61.0,70.0,58.0,331.0
77571,20162,URBANO,N,A,TÉCNICO/ACADÉMICO,120400000111,120400000111,20400,TARDE,OFICIAL,20.0,20400.0,PUBLICAR,F,COLOMBIA,Uno,Secundaria (Bachillerato) incompleta,No sabe,Estrato 1,Dos,No,No,No,Si,63.0,55.0,54.0,54.0,53.0,273.0
77572,20142,RURAL,N,A,ACADÉMICO,220013000395,220013000395,20013,MAÑANA,OFICIAL,20.0,20013.0,PUBLICAR,M,COLOMBIA,Dos,Ninguno,Ninguno,Estrato 1,Siete,No,Si,No,No,41.0,52.0,41.0,42.0,43.0,221.0
77573,20142,URBANO,N,A,TÉCNICO,120001068194,120001068194,20001,MAÑANA,OFICIAL,20.0,20001.0,PUBLICAR,F,COLOMBIA,Dos,Ninguno,Ninguno,Estrato 1,Cuatro,No,No,No,Si,41.0,38.0,40.0,37.0,41.0,196.0
77574,20194,URBANO,N,A,TÉCNICO/ACADÉMICO,120045000210,120045000210,20045,MAÑANA,OFICIAL,20.0,20045.0,PUBLICAR,M,COLOMBIA,Tres,No sabe,Primaria incompleta,Estrato 3,1 a 2,Si,Si,Si,Si,38.0,39.0,31.0,35.0,33.0,174.0

In [88]:
# Set column types to clean nulls

'''filtered_df["estu_fechanacimiento"] = pd.to_datetime(
    filtered_df["estu_fechanacimiento"],
    errors="coerce",
    dayfirst=True
)'''

filtered_df["estu_cod_reside_depto"] = (
    pd.to_numeric(filtered_df["estu_cod_reside_depto"], errors="coerce")
    .astype("Int64")
    .astype("string")
)

filtered_df["estu_cod_reside_mcpio"] = (
    pd.to_numeric(filtered_df["estu_cod_reside_mcpio"], errors="coerce")
    .astype("Int64")
    .astype("string")
)

# Set column types to clean nulls
filtered_df = filtered_df.astype({
    "periodo": "category",

    "cole_area_ubicacion": "category", # boolean in the future
    "cole_bilingue": "category", # boolean in the future
    "cole_calendario": "category", # boolean in the future
    "cole_caracter": "category",

    "cole_cod_dane_establecimiento": "string", # TODO: is this actually categorical?
    "cole_cod_dane_sede": "string",
    "cole_cod_mcpio_ubicacion": "string",

    "cole_jornada": "category",
    "cole_naturaleza": "category", # boolean in the future

    "estu_estadoinvestigacion": "category", # keep only PUBLICAR then remove

    "estu_genero": "category", # boolean in the future
    "estu_nacionalidad": "category",

    "fami_cuartoshogar": "string", # clean and send to category later

    "fami_educacionmadre": "category", 
    "fami_educacionpadre": "category", 
    "fami_estratovivienda": "category", 

    "fami_personashogar": "category", # clean and send to category/int later

    "fami_tieneautomovil": "category", # boolean in the future
    "fami_tienecomputador": "category", # boolean in the future
    "fami_tieneinternet": "category", # boolean in the future
    "fami_tienelavadora": "category", # boolean in the future

    # Nullable integers
    "punt_ingles": "Int64",
    "punt_matematicas": "Int64",
    "punt_sociales_ciudadanas": "Int64",
    "punt_c_naturales": "Int64",
    "punt_lectura_critica": "Int64",
    "punt_global": "Int64"
})
filtered_df.dtypes

periodo                          category
cole_area_ubicacion              category
cole_bilingue                    category
cole_calendario                  category
cole_caracter                    category
cole_cod_dane_establecimiento      string
cole_cod_dane_sede                 string
cole_cod_mcpio_ubicacion           string
cole_jornada                     category
cole_naturaleza                  category
estu_cod_reside_depto              string
estu_cod_reside_mcpio              string
estu_estadoinvestigacion         category
estu_genero                      category
estu_nacionalidad                category
fami_cuartoshogar                  string
fami_educacionmadre              category
fami_educacionpadre              category
fami_estratovivienda             category
fami_personashogar               category
fami_tieneautomovil              category
fami_tienecomputador             category
fami_tieneinternet               category
fami_tienelavadora               category
punt_ingles                         Int64
punt_matematicas                    Int64
punt_sociales_ciudadanas            Int64
punt_c_naturales                    Int64
punt_lectura_critica                Int64
punt_global                         Int64
dtype: object

In [89]:
# Clean all rows with any null values already present in the data
filtered_df = filtered_df.dropna(axis=0, how="any").reset_index(drop=True)
filtered_df.head()

,periodo,cole_area_ubicacion,cole_bilingue,cole_calendario,cole_caracter,cole_cod_dane_establecimiento,cole_cod_dane_sede,cole_cod_mcpio_ubicacion,cole_jornada,cole_naturaleza,estu_cod_reside_depto,estu_cod_reside_mcpio,estu_estadoinvestigacion,estu_genero,estu_nacionalidad,fami_cuartoshogar,fami_educacionmadre,fami_educacionpadre,fami_estratovivienda,fami_personashogar,fami_tieneautomovil,fami_tienecomputador,fami_tieneinternet,fami_tienelavadora,punt_ingles,punt_matematicas,punt_sociales_ciudadanas,punt_c_naturales,punt_lectura_critica,punt_global
0,20224,URBANO,N,A,ACADÉMICO,120001006768,120001006768,20001,MAÑANA,OFICIAL,20,20001,PUBLICAR,F,COLOMBIA,Dos,Primaria completa,Primaria incompleta,Estrato 4,3 a 4,Si,No,Si,Si,42,49,48,45,47,234
1,20224,RURAL,N,A,ACADÉMICO,220001067435,220001067435,20001,UNICA,OFICIAL,20,20001,PUBLICAR,M,COLOMBIA,Cuatro,Primaria completa,Secundaria (Bachillerato) incompleta,Estrato 1,3 a 4,Si,No,Si,Si,55,65,56,67,54,300
2,20224,RURAL,N,A,TÉCNICO/ACADÉMICO,220175017801,220175017801,20175,UNICA,OFICIAL,20,20175,PUBLICAR,M,COLOMBIA,Dos,Primaria incompleta,Primaria incompleta,Estrato 1,5 a 6,No,No,No,No,44,44,45,34,48,214
3,20224,URBANO,N,A,TÉCNICO,120001001201,120001001201,20001,TARDE,OFICIAL,20,20001,PUBLICAR,F,COLOMBIA,Dos,Técnica o tecnológica completa,Secundaria (Bachillerato) incompleta,Estrato 2,3 a 4,No,Si,Si,Si,41,40,36,42,50,210
4,20224,URBANO,N,A,TÉCNICO/ACADÉMICO,120295000061,120295000061,20295,UNICA,OFICIAL,20,20295,PUBLICAR,F,COLOMBIA,Tres,Educación profesional completa,Educación profesional completa,Estrato 2,5 a 6,No,No,No,Si,31,40,30,33,44,182

In [90]:
# Remove estu_estadoinvestigacion rows that are not PUBLICAR and estu_cod_reside_depto that are not 20
filtered_df = filtered_df[(filtered_df["estu_estadoinvestigacion"] == "PUBLICAR") & (filtered_df["estu_cod_reside_depto"] == "20")].reset_index(drop=True)
filtered_df

,periodo,cole_area_ubicacion,cole_bilingue,cole_calendario,cole_caracter,cole_cod_dane_establecimiento,cole_cod_dane_sede,cole_cod_mcpio_ubicacion,cole_jornada,cole_naturaleza,estu_cod_reside_depto,estu_cod_reside_mcpio,estu_estadoinvestigacion,estu_genero,estu_nacionalidad,fami_cuartoshogar,fami_educacionmadre,fami_educacionpadre,fami_estratovivienda,fami_personashogar,fami_tieneautomovil,fami_tienecomputador,fami_tieneinternet,fami_tienelavadora,punt_ingles,punt_matematicas,punt_sociales_ciudadanas,punt_c_naturales,punt_lectura_critica,punt_global
0,20224,URBANO,N,A,ACADÉMICO,120001006768,120001006768,20001,MAÑANA,OFICIAL,20,20001,PUBLICAR,F,COLOMBIA,Dos,Primaria completa,Primaria incompleta,Estrato 4,3 a 4,Si,No,Si,Si,42,49,48,45,47,234
1,20224,RURAL,N,A,ACADÉMICO,220001067435,220001067435,20001,UNICA,OFICIAL,20,20001,PUBLICAR,M,COLOMBIA,Cuatro,Primaria completa,Secundaria (Bachillerato) incompleta,Estrato 1,3 a 4,Si,No,Si,Si,55,65,56,67,54,300
2,20224,RURAL,N,A,TÉCNICO/ACADÉMICO,220175017801,220175017801,20175,UNICA,OFICIAL,20,20175,PUBLICAR,M,COLOMBIA,Dos,Primaria incompleta,Primaria incompleta,Estrato 1,5 a 6,No,No,No,No,44,44,45,34,48,214
3,20224,URBANO,N,A,TÉCNICO,120001001201,120001001201,20001,TARDE,OFICIAL,20,20001,PUBLICAR,F,COLOMBIA,Dos,Técnica o tecnológica completa,Secundaria (Bachillerato) incompleta,Estrato 2,3 a 4,No,Si,Si,Si,41,40,36,42,50,210
4,20224,URBANO,N,A,TÉCNICO/ACADÉMICO,120295000061,120295000061,20295,UNICA,OFICIAL,20,20295,PUBLICAR,F,COLOMBIA,Tres,Educación profesional completa,Educación profesional completa,Estrato 2,5 a 6,No,No,No,Si,31,40,30,33,44,182
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63122,20162,URBANO,N,A,ACADÉMICO,120001000921,120001000921,20001,TARDE,OFICIAL,20,20001,PUBLICAR,F,COLOMBIA,Dos,Primaria completa,Secundaria (Bachillerato) completa,Estrato 1,Cuatro,No,No,No,No,71,74,61,70,58,331
63123,20162,URBANO,N,A,TÉCNICO/ACADÉMICO,120400000111,120400000111,20400,TARDE,OFICIAL,20,20400,PUBLICAR,F,COLOMBIA,Uno,Secundaria (Bachillerato) incompleta,No sabe,Estrato 1,Dos,No,No,No,Si,63,55,54,54,53,273
63124,20142,RURAL,N,A,ACADÉMICO,220013000395,220013000395,20013,MAÑANA,OFICIAL,20,20013,PUBLICAR,M,COLOMBIA,Dos,Ninguno,Ninguno,Estrato 1,Siete,No,Si,No,No,41,52,41,42,43,221
63125,20142,URBANO,N,A,TÉCNICO,120001068194,120001068194,20001,MAÑANA,OFICIAL,20,20001,PUBLICAR,F,COLOMBIA,Dos,Ninguno,Ninguno,Estrato 1,Cuatro,No,No,No,Si,41,38,40,37,41,196
63126,20194,URBANO,N,A,TÉCNICO/ACADÉMICO,120045000210,120045000210,20045,MAÑANA,OFICIAL,20,20045,PUBLICAR,M,COLOMBIA,Tres,No sabe,Primaria incompleta,Estrato 3,1 a 2,Si,Si,Si,Si,38,39,31,35,33,174

In [91]:
# Remove column estu_estadoinvestigacion and estu_cod_reside_depto
filtered_df = filtered_df.drop(columns=["estu_estadoinvestigacion", "estu_cod_reside_depto"])
filtered_df

,periodo,cole_area_ubicacion,cole_bilingue,cole_calendario,cole_caracter,cole_cod_dane_establecimiento,cole_cod_dane_sede,cole_cod_mcpio_ubicacion,cole_jornada,cole_naturaleza,estu_cod_reside_mcpio,estu_genero,estu_nacionalidad,fami_cuartoshogar,fami_educacionmadre,fami_educacionpadre,fami_estratovivienda,fami_personashogar,fami_tieneautomovil,fami_tienecomputador,fami_tieneinternet,fami_tienelavadora,punt_ingles,punt_matematicas,punt_sociales_ciudadanas,punt_c_naturales,punt_lectura_critica,punt_global
0,20224,URBANO,N,A,ACADÉMICO,120001006768,120001006768,20001,MAÑANA,OFICIAL,20001,F,COLOMBIA,Dos,Primaria completa,Primaria incompleta,Estrato 4,3 a 4,Si,No,Si,Si,42,49,48,45,47,234
1,20224,RURAL,N,A,ACADÉMICO,220001067435,220001067435,20001,UNICA,OFICIAL,20001,M,COLOMBIA,Cuatro,Primaria completa,Secundaria (Bachillerato) incompleta,Estrato 1,3 a 4,Si,No,Si,Si,55,65,56,67,54,300
2,20224,RURAL,N,A,TÉCNICO/ACADÉMICO,220175017801,220175017801,20175,UNICA,OFICIAL,20175,M,COLOMBIA,Dos,Primaria incompleta,Primaria incompleta,Estrato 1,5 a 6,No,No,No,No,44,44,45,34,48,214
3,20224,URBANO,N,A,TÉCNICO,120001001201,120001001201,20001,TARDE,OFICIAL,20001,F,COLOMBIA,Dos,Técnica o tecnológica completa,Secundaria (Bachillerato) incompleta,Estrato 2,3 a 4,No,Si,Si,Si,41,40,36,42,50,210
4,20224,URBANO,N,A,TÉCNICO/ACADÉMICO,120295000061,120295000061,20295,UNICA,OFICIAL,20295,F,COLOMBIA,Tres,Educación profesional completa,Educación profesional completa,Estrato 2,5 a 6,No,No,No,Si,31,40,30,33,44,182
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63122,20162,URBANO,N,A,ACADÉMICO,120001000921,120001000921,20001,TARDE,OFICIAL,20001,F,COLOMBIA,Dos,Primaria completa,Secundaria (Bachillerato) completa,Estrato 1,Cuatro,No,No,No,No,71,74,61,70,58,331
63123,20162,URBANO,N,A,TÉCNICO/ACADÉMICO,120400000111,120400000111,20400,TARDE,OFICIAL,20400,F,COLOMBIA,Uno,Secundaria (Bachillerato) incompleta,No sabe,Estrato 1,Dos,No,No,No,Si,63,55,54,54,53,273
63124,20142,RURAL,N,A,ACADÉMICO,220013000395,220013000395,20013,MAÑANA,OFICIAL,20013,M,COLOMBIA,Dos,Ninguno,Ninguno,Estrato 1,Siete,No,Si,No,No,41,52,41,42,43,221
63125,20142,URBANO,N,A,TÉCNICO,120001068194,120001068194,20001,MAÑANA,OFICIAL,20001,F,COLOMBIA,Dos,Ninguno,Ninguno,Estrato 1,Cuatro,No,No,No,Si,41,38,40,37,41,196
63126,20194,URBANO,N,A,TÉCNICO/ACADÉMICO,120045000210,120045000210,20045,MAÑANA,OFICIAL,20045,M,COLOMBIA,Tres,No sabe,Primaria incompleta,Estrato 3,1 a 2,Si,Si,Si,Si,38,39,31,35,33,174

In [92]:
# export cleaned data to csv
filtered_df.to_csv("../data/filtered_icfes_data_cesar.csv", index=False)